name: immersive
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - streamlit>=1.31.0
  - numpy
  - pillow>=11.1.0
  - requests>=2.31.0
  - pytest>=7.4.0
  - pip:
    - opencv-python>=4.5.5
    - python-dotenv>=1.0.0
    - together>=1.4.1
    - google-generativeai>=0.3.0
